#! /bin/bash

## delete a NX user on the remote machine
## usage:
## NXdeluser username 

if [ "$NXset" != "set" ]; then
    source $NXHOME/NXsetup
fi
ssh $DSKaccount "sudo /usr/NX/bin/nxserver --userdel $1; sudo userdel -rf $1"
