#! /bin/bash

## set up the machines and keys

export ABQ_PATH2=/Users/mohammadshoeybi/Documents/Abaqual/repos/abq_web
export DSKmachine=ec2-50-18-244-56.us-west-1.compute.amazonaws.com ;

export NXDIR=$ABQ_PATH2/nxscripts
export DSKaccount=ubuntu@$DSKmachine ;
export DSKkey=$NXDIR/keys/AWS_desktop_hosts.pem
export SESSIONDIR=$ABQ_PATH2/demo/desktop/static/session

export NXset=set ;

