#! /bin/bash

## prepare a node (given by NXsetup) remotely 

## set the nodes and keys 
if [ "$NXset" != "set" ]; then
    source $NXDIR/NXsetup
fi
## make public keys if not made already 
if [ -ne $HOME/.ssh/id_rsa.pub ]; then
    ssh-keygen -t rsa ;
fi
## set proper permissions for the keys
chmod 400 $DSKkey
## set passwordless ssh
cat $HOME/.ssh/id_rsa.pub | ssh -i $DSKkey $DSKaccount 'cat >> $HOME/.ssh/authorized_keys' ;
## remotely run prepareAWS.sh
$NXHOME/runSSH prepareAWS.sh $DSKaccount ;
